version: '3.2'

services:
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: mygo
      POSTGRES_PASSWORD: secret
    ports:
      - 2010:5432
    volumes:
      - ~/.docker-volumes/mygo/posgresql/data:/var/lib/posgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 2020:8080

  mygo:
    build: .
    depends_on:
      - postgres
      - adminer
    links:
      - postgres
    volumes:
      - .:/go/src/github.com/mihailo-misic/learning-docker/01
    ports:
      - 2000:8000
